[2021-11-25 23:03:38,236] {processor.py:163} INFO - Started process (PID=5905) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:03:38,236] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:03:38,237] {logging_mixin.py:109} INFO - [2021-11-25 23:03:38,237] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:03:38,256] {logging_mixin.py:109} INFO - [2021-11-25 23:03:38,252] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:03:38,267] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:03:38,270] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-25 23:05:03,797] {processor.py:163} INFO - Started process (PID=6039) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:05:03,800] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:05:03,800] {logging_mixin.py:109} INFO - [2021-11-25 23:05:03,800] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:05:03,816] {logging_mixin.py:109} INFO - [2021-11-25 23:05:03,814] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:05:03,829] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:05:03,831] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-25 23:06:26,807] {processor.py:163} INFO - Started process (PID=6146) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:06:26,808] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:06:26,808] {logging_mixin.py:109} INFO - [2021-11-25 23:06:26,808] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:06:26,824] {logging_mixin.py:109} INFO - [2021-11-25 23:06:26,821] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:06:26,836] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:06:26,838] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-25 23:07:48,997] {processor.py:163} INFO - Started process (PID=6252) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:07:48,999] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:07:48,999] {logging_mixin.py:109} INFO - [2021-11-25 23:07:48,999] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:07:49,016] {logging_mixin.py:109} INFO - [2021-11-25 23:07:49,014] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:07:49,028] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:07:49,031] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-25 23:09:10,032] {processor.py:163} INFO - Started process (PID=6377) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:09:10,033] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:09:10,033] {logging_mixin.py:109} INFO - [2021-11-25 23:09:10,033] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:09:10,049] {logging_mixin.py:109} INFO - [2021-11-25 23:09:10,046] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:09:10,061] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:09:10,063] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-25 23:10:33,901] {processor.py:163} INFO - Started process (PID=6494) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:10:33,901] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:10:33,902] {logging_mixin.py:109} INFO - [2021-11-25 23:10:33,902] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:10:33,916] {logging_mixin.py:109} INFO - [2021-11-25 23:10:33,914] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:10:33,928] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:10:33,931] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-25 23:11:58,395] {processor.py:163} INFO - Started process (PID=7315) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:11:58,396] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:11:58,396] {logging_mixin.py:109} INFO - [2021-11-25 23:11:58,396] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:11:58,412] {logging_mixin.py:109} INFO - [2021-11-25 23:11:58,409] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:11:58,425] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:11:58,428] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-25 23:13:20,161] {processor.py:163} INFO - Started process (PID=7434) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:13:20,162] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:13:20,162] {logging_mixin.py:109} INFO - [2021-11-25 23:13:20,162] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:13:20,177] {logging_mixin.py:109} INFO - [2021-11-25 23:13:20,175] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:13:20,189] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:13:20,192] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-25 23:14:43,383] {processor.py:163} INFO - Started process (PID=7564) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:14:43,384] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:14:43,384] {logging_mixin.py:109} INFO - [2021-11-25 23:14:43,384] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:14:43,401] {logging_mixin.py:109} INFO - [2021-11-25 23:14:43,398] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:14:43,413] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:14:43,416] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-25 23:16:08,291] {processor.py:163} INFO - Started process (PID=7669) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:16:08,291] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-25 23:16:08,292] {logging_mixin.py:109} INFO - [2021-11-25 23:16:08,292] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:16:08,310] {logging_mixin.py:109} INFO - [2021-11-25 23:16:08,307] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-25 23:16:08,322] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-25 23:16:08,325] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 06:21:12,999] {processor.py:163} INFO - Started process (PID=8208) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 06:21:12,999] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 06:21:12,999] {logging_mixin.py:109} INFO - [2021-11-26 06:21:12,999] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 06:21:13,015] {logging_mixin.py:109} INFO - [2021-11-26 06:21:13,013] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 06:21:13,029] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 06:21:13,032] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 08:22:24,633] {processor.py:163} INFO - Started process (PID=8494) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:22:24,633] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:22:24,633] {logging_mixin.py:109} INFO - [2021-11-26 08:22:24,633] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:22:24,650] {logging_mixin.py:109} INFO - [2021-11-26 08:22:24,648] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:22:24,663] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:22:24,665] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 08:26:05,790] {processor.py:163} INFO - Started process (PID=8766) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:26:05,791] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:26:05,791] {logging_mixin.py:109} INFO - [2021-11-26 08:26:05,791] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:26:05,810] {logging_mixin.py:109} INFO - [2021-11-26 08:26:05,807] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:26:05,822] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:26:05,824] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 08:27:46,051] {processor.py:163} INFO - Started process (PID=8949) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:27:46,052] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:27:46,052] {logging_mixin.py:109} INFO - [2021-11-26 08:27:46,052] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:27:46,072] {logging_mixin.py:109} INFO - [2021-11-26 08:27:46,068] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:27:46,083] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:27:46,086] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.036 seconds
[2021-11-26 08:30:19,484] {processor.py:163} INFO - Started process (PID=9163) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:30:19,484] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:30:19,484] {logging_mixin.py:109} INFO - [2021-11-26 08:30:19,484] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:30:19,499] {logging_mixin.py:109} INFO - [2021-11-26 08:30:19,496] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:30:19,511] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:30:19,514] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 08:32:50,484] {processor.py:163} INFO - Started process (PID=9345) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:32:50,485] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:32:50,485] {logging_mixin.py:109} INFO - [2021-11-26 08:32:50,485] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:32:50,502] {logging_mixin.py:109} INFO - [2021-11-26 08:32:50,499] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:32:50,515] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:32:50,518] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-26 08:34:55,329] {processor.py:163} INFO - Started process (PID=9486) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:34:55,330] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:34:55,330] {logging_mixin.py:109} INFO - [2021-11-26 08:34:55,330] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:34:55,363] {logging_mixin.py:109} INFO - [2021-11-26 08:34:55,360] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:34:55,376] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:34:55,379] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.050 seconds
[2021-11-26 08:36:55,869] {processor.py:163} INFO - Started process (PID=9586) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:36:55,889] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:36:55,900] {logging_mixin.py:109} INFO - [2021-11-26 08:36:55,900] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:36:55,971] {logging_mixin.py:109} INFO - [2021-11-26 08:36:55,969] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:36:56,023] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:36:56,040] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.173 seconds
[2021-11-26 08:38:35,502] {processor.py:163} INFO - Started process (PID=9737) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:38:35,503] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 08:38:35,503] {logging_mixin.py:109} INFO - [2021-11-26 08:38:35,503] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:38:35,520] {logging_mixin.py:109} INFO - [2021-11-26 08:38:35,517] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 08:38:35,532] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 08:38:35,535] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 09:11:30,239] {processor.py:163} INFO - Started process (PID=9967) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 09:11:30,240] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 09:11:30,240] {logging_mixin.py:109} INFO - [2021-11-26 09:11:30,240] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 09:11:30,259] {logging_mixin.py:109} INFO - [2021-11-26 09:11:30,257] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 09:11:30,273] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 09:11:30,275] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.036 seconds
[2021-11-26 11:20:14,208] {processor.py:163} INFO - Started process (PID=10299) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:20:14,208] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 11:20:14,209] {logging_mixin.py:109} INFO - [2021-11-26 11:20:14,208] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:20:14,227] {logging_mixin.py:109} INFO - [2021-11-26 11:20:14,224] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 11:20:14,239] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:20:14,242] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 11:21:35,494] {processor.py:163} INFO - Started process (PID=10442) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:21:35,495] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 11:21:35,496] {logging_mixin.py:109} INFO - [2021-11-26 11:21:35,496] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:21:35,514] {logging_mixin.py:109} INFO - [2021-11-26 11:21:35,511] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 11:21:35,526] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:21:35,529] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 11:22:59,849] {processor.py:163} INFO - Started process (PID=10578) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:22:59,850] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 11:22:59,850] {logging_mixin.py:109} INFO - [2021-11-26 11:22:59,850] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:22:59,868] {logging_mixin.py:109} INFO - [2021-11-26 11:22:59,865] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 11:22:59,879] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:22:59,882] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 11:24:24,037] {processor.py:163} INFO - Started process (PID=10702) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:24:24,038] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 11:24:24,038] {logging_mixin.py:109} INFO - [2021-11-26 11:24:24,038] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:24:24,053] {logging_mixin.py:109} INFO - [2021-11-26 11:24:24,051] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 11:24:24,065] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:24:24,068] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 11:25:46,635] {processor.py:163} INFO - Started process (PID=10827) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:25:46,637] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 11:25:46,637] {logging_mixin.py:109} INFO - [2021-11-26 11:25:46,637] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:25:46,654] {logging_mixin.py:109} INFO - [2021-11-26 11:25:46,652] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 11:25:46,666] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 11:25:46,669] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:20:37,317] {processor.py:163} INFO - Started process (PID=11030) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:20:37,317] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:20:37,318] {logging_mixin.py:109} INFO - [2021-11-26 12:20:37,318] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:20:37,335] {logging_mixin.py:109} INFO - [2021-11-26 12:20:37,332] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:20:37,346] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:20:37,349] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:21:47,570] {processor.py:163} INFO - Started process (PID=11224) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:21:47,571] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:21:47,571] {logging_mixin.py:109} INFO - [2021-11-26 12:21:47,571] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:21:47,586] {logging_mixin.py:109} INFO - [2021-11-26 12:21:47,583] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:21:47,599] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:21:47,601] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 12:23:12,294] {processor.py:163} INFO - Started process (PID=11346) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:23:12,295] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:23:12,295] {logging_mixin.py:109} INFO - [2021-11-26 12:23:12,295] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:23:12,311] {logging_mixin.py:109} INFO - [2021-11-26 12:23:12,308] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:23:12,323] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:23:12,325] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 12:24:35,252] {processor.py:163} INFO - Started process (PID=11487) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:24:35,253] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:24:35,253] {logging_mixin.py:109} INFO - [2021-11-26 12:24:35,253] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:24:35,270] {logging_mixin.py:109} INFO - [2021-11-26 12:24:35,267] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:24:35,282] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:24:35,285] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:26:00,757] {processor.py:163} INFO - Started process (PID=11627) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:26:00,758] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:26:00,758] {logging_mixin.py:109} INFO - [2021-11-26 12:26:00,758] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:26:00,772] {logging_mixin.py:109} INFO - [2021-11-26 12:26:00,770] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:26:00,784] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:26:00,786] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 12:27:32,232] {processor.py:163} INFO - Started process (PID=11764) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:27:32,233] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:27:32,233] {logging_mixin.py:109} INFO - [2021-11-26 12:27:32,233] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:27:32,249] {logging_mixin.py:109} INFO - [2021-11-26 12:27:32,246] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:27:32,260] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:27:32,263] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 12:28:59,428] {processor.py:163} INFO - Started process (PID=11961) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:28:59,430] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:28:59,430] {logging_mixin.py:109} INFO - [2021-11-26 12:28:59,430] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:28:59,446] {logging_mixin.py:109} INFO - [2021-11-26 12:28:59,443] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:28:59,458] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:28:59,460] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 12:30:25,835] {processor.py:163} INFO - Started process (PID=12104) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:30:25,836] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:30:25,836] {logging_mixin.py:109} INFO - [2021-11-26 12:30:25,836] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:30:25,853] {logging_mixin.py:109} INFO - [2021-11-26 12:30:25,850] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:30:25,865] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:30:25,868] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:31:50,696] {processor.py:163} INFO - Started process (PID=12229) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:31:50,697] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:31:50,697] {logging_mixin.py:109} INFO - [2021-11-26 12:31:50,697] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:31:50,715] {logging_mixin.py:109} INFO - [2021-11-26 12:31:50,712] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:31:50,727] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:31:50,729] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-26 12:33:13,773] {processor.py:163} INFO - Started process (PID=12333) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:33:13,774] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:33:13,774] {logging_mixin.py:109} INFO - [2021-11-26 12:33:13,774] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:33:13,791] {logging_mixin.py:109} INFO - [2021-11-26 12:33:13,789] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:33:13,803] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:33:13,805] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:34:44,144] {processor.py:163} INFO - Started process (PID=12491) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:34:44,153] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:34:44,153] {logging_mixin.py:109} INFO - [2021-11-26 12:34:44,153] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:34:44,169] {logging_mixin.py:109} INFO - [2021-11-26 12:34:44,166] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:34:44,183] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:34:44,185] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.042 seconds
[2021-11-26 12:36:16,604] {processor.py:163} INFO - Started process (PID=12688) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:36:16,604] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:36:16,605] {logging_mixin.py:109} INFO - [2021-11-26 12:36:16,605] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:36:16,621] {logging_mixin.py:109} INFO - [2021-11-26 12:36:16,618] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:36:16,633] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:36:16,636] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 12:37:43,675] {processor.py:163} INFO - Started process (PID=12840) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:37:43,676] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:37:43,676] {logging_mixin.py:109} INFO - [2021-11-26 12:37:43,676] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:37:43,697] {logging_mixin.py:109} INFO - [2021-11-26 12:37:43,694] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:37:43,709] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:37:43,713] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.038 seconds
[2021-11-26 12:39:13,808] {processor.py:163} INFO - Started process (PID=12979) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:39:13,809] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:39:13,809] {logging_mixin.py:109} INFO - [2021-11-26 12:39:13,809] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:39:13,826] {logging_mixin.py:109} INFO - [2021-11-26 12:39:13,824] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:39:13,839] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:39:13,841] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 12:40:41,371] {processor.py:163} INFO - Started process (PID=13126) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:40:41,372] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:40:41,372] {logging_mixin.py:109} INFO - [2021-11-26 12:40:41,372] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:40:41,387] {logging_mixin.py:109} INFO - [2021-11-26 12:40:41,384] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:40:41,399] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:40:41,401] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 12:42:06,687] {processor.py:163} INFO - Started process (PID=13238) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:42:06,688] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:42:06,688] {logging_mixin.py:109} INFO - [2021-11-26 12:42:06,688] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:42:06,703] {logging_mixin.py:109} INFO - [2021-11-26 12:42:06,701] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:42:06,719] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:42:06,723] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.037 seconds
[2021-11-26 12:43:38,382] {processor.py:163} INFO - Started process (PID=13433) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:43:38,382] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:43:38,383] {logging_mixin.py:109} INFO - [2021-11-26 12:43:38,383] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:43:38,397] {logging_mixin.py:109} INFO - [2021-11-26 12:43:38,395] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:43:38,410] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:43:38,412] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 12:45:10,807] {processor.py:163} INFO - Started process (PID=13547) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:45:10,808] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:45:10,808] {logging_mixin.py:109} INFO - [2021-11-26 12:45:10,808] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:45:10,843] {logging_mixin.py:109} INFO - [2021-11-26 12:45:10,836] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:45:10,860] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:45:10,864] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.058 seconds
[2021-11-26 12:46:39,586] {processor.py:163} INFO - Started process (PID=13686) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:46:39,586] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:46:39,586] {logging_mixin.py:109} INFO - [2021-11-26 12:46:39,586] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:46:39,602] {logging_mixin.py:109} INFO - [2021-11-26 12:46:39,600] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:46:39,614] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:46:39,617] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 12:48:06,731] {processor.py:163} INFO - Started process (PID=13820) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:48:06,732] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:48:06,732] {logging_mixin.py:109} INFO - [2021-11-26 12:48:06,732] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:48:06,750] {logging_mixin.py:109} INFO - [2021-11-26 12:48:06,747] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:48:06,763] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:48:06,766] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 12:49:38,843] {processor.py:163} INFO - Started process (PID=13964) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:49:38,843] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:49:38,844] {logging_mixin.py:109} INFO - [2021-11-26 12:49:38,844] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:49:38,860] {logging_mixin.py:109} INFO - [2021-11-26 12:49:38,857] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:49:38,872] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:49:38,875] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 12:51:06,948] {processor.py:163} INFO - Started process (PID=14141) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:51:06,949] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 12:51:06,949] {logging_mixin.py:109} INFO - [2021-11-26 12:51:06,949] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:51:06,967] {logging_mixin.py:109} INFO - [2021-11-26 12:51:06,964] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 12:51:06,979] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 12:51:06,982] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 13:02:39,419] {processor.py:163} INFO - Started process (PID=14396) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:02:39,419] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:02:39,420] {logging_mixin.py:109} INFO - [2021-11-26 13:02:39,420] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:02:39,436] {logging_mixin.py:109} INFO - [2021-11-26 13:02:39,433] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:02:39,448] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:02:39,450] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 13:03:48,694] {processor.py:163} INFO - Started process (PID=14491) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:03:48,695] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:03:48,696] {logging_mixin.py:109} INFO - [2021-11-26 13:03:48,696] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:03:48,713] {logging_mixin.py:109} INFO - [2021-11-26 13:03:48,710] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:03:48,725] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:03:48,727] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 13:05:13,521] {processor.py:163} INFO - Started process (PID=14606) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:05:13,522] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:05:13,522] {logging_mixin.py:109} INFO - [2021-11-26 13:05:13,522] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:05:13,539] {logging_mixin.py:109} INFO - [2021-11-26 13:05:13,536] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:05:13,552] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:05:13,555] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-26 13:06:35,159] {processor.py:163} INFO - Started process (PID=14708) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:06:35,159] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:06:35,160] {logging_mixin.py:109} INFO - [2021-11-26 13:06:35,160] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:06:35,175] {logging_mixin.py:109} INFO - [2021-11-26 13:06:35,174] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:06:35,187] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:06:35,190] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 13:08:52,979] {processor.py:163} INFO - Started process (PID=15045) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:08:52,979] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:08:52,980] {logging_mixin.py:109} INFO - [2021-11-26 13:08:52,980] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:08:53,002] {logging_mixin.py:109} INFO - [2021-11-26 13:08:53,000] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:08:53,042] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:08:53,046] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.068 seconds
[2021-11-26 13:15:01,175] {processor.py:163} INFO - Started process (PID=15315) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:15:01,176] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:15:01,176] {logging_mixin.py:109} INFO - [2021-11-26 13:15:01,176] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:15:01,197] {logging_mixin.py:109} INFO - [2021-11-26 13:15:01,195] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:15:01,209] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:15:01,212] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.037 seconds
[2021-11-26 13:19:08,011] {processor.py:163} INFO - Started process (PID=15493) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:19:08,011] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:19:08,011] {logging_mixin.py:109} INFO - [2021-11-26 13:19:08,011] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:19:08,030] {logging_mixin.py:109} INFO - [2021-11-26 13:19:08,027] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:19:08,042] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:19:08,044] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-26 13:21:12,256] {processor.py:163} INFO - Started process (PID=15696) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:21:12,256] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 13:21:12,256] {logging_mixin.py:109} INFO - [2021-11-26 13:21:12,256] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:21:12,272] {logging_mixin.py:109} INFO - [2021-11-26 13:21:12,270] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 13:21:12,284] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 13:21:12,287] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 15:32:33,229] {processor.py:163} INFO - Started process (PID=16026) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:32:33,231] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 15:32:33,231] {logging_mixin.py:109} INFO - [2021-11-26 15:32:33,231] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:32:33,278] {logging_mixin.py:109} INFO - [2021-11-26 15:32:33,270] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 15:32:33,291] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:32:33,294] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.065 seconds
[2021-11-26 15:34:05,506] {processor.py:163} INFO - Started process (PID=16150) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:34:05,508] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 15:34:05,508] {logging_mixin.py:109} INFO - [2021-11-26 15:34:05,508] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:34:05,540] {logging_mixin.py:109} INFO - [2021-11-26 15:34:05,526] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 15:34:05,552] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 15:34:05,554] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.049 seconds
[2021-11-26 16:25:57,588] {processor.py:163} INFO - Started process (PID=16353) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:25:57,588] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:25:57,588] {logging_mixin.py:109} INFO - [2021-11-26 16:25:57,588] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:25:57,605] {logging_mixin.py:109} INFO - [2021-11-26 16:25:57,603] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:25:57,619] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:25:57,622] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 16:29:14,771] {processor.py:163} INFO - Started process (PID=16547) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:29:14,772] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:29:14,772] {logging_mixin.py:109} INFO - [2021-11-26 16:29:14,772] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:29:14,789] {logging_mixin.py:109} INFO - [2021-11-26 16:29:14,786] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:29:14,802] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:29:14,806] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 16:30:36,855] {processor.py:163} INFO - Started process (PID=16669) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:30:36,856] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:30:36,856] {logging_mixin.py:109} INFO - [2021-11-26 16:30:36,856] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:30:36,872] {logging_mixin.py:109} INFO - [2021-11-26 16:30:36,870] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:30:36,885] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:30:36,887] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 16:32:02,755] {processor.py:163} INFO - Started process (PID=16835) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:32:02,755] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:32:02,755] {logging_mixin.py:109} INFO - [2021-11-26 16:32:02,755] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:32:02,774] {logging_mixin.py:109} INFO - [2021-11-26 16:32:02,771] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:32:02,787] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:32:02,790] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.036 seconds
[2021-11-26 16:33:23,942] {processor.py:163} INFO - Started process (PID=16936) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:33:23,943] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:33:23,943] {logging_mixin.py:109} INFO - [2021-11-26 16:33:23,943] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:33:23,960] {logging_mixin.py:109} INFO - [2021-11-26 16:33:23,958] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:33:23,972] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:33:23,975] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 16:34:45,304] {processor.py:163} INFO - Started process (PID=17041) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:34:45,305] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:34:45,305] {logging_mixin.py:109} INFO - [2021-11-26 16:34:45,305] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:34:45,322] {logging_mixin.py:109} INFO - [2021-11-26 16:34:45,318] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:34:45,335] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:34:45,337] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 16:36:09,049] {processor.py:163} INFO - Started process (PID=17159) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:36:09,050] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:36:09,050] {logging_mixin.py:109} INFO - [2021-11-26 16:36:09,050] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:36:09,067] {logging_mixin.py:109} INFO - [2021-11-26 16:36:09,065] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:36:09,080] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:36:09,083] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.034 seconds
[2021-11-26 16:37:31,353] {processor.py:163} INFO - Started process (PID=17270) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:37:31,353] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:37:31,353] {logging_mixin.py:109} INFO - [2021-11-26 16:37:31,353] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:37:31,369] {logging_mixin.py:109} INFO - [2021-11-26 16:37:31,367] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:37:31,381] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:37:31,384] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 16:38:53,472] {processor.py:163} INFO - Started process (PID=17401) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:38:53,473] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:38:53,474] {logging_mixin.py:109} INFO - [2021-11-26 16:38:53,474] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:38:53,491] {logging_mixin.py:109} INFO - [2021-11-26 16:38:53,490] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:38:53,504] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:38:53,507] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 16:40:17,259] {processor.py:163} INFO - Started process (PID=17502) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:40:17,260] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:40:17,260] {logging_mixin.py:109} INFO - [2021-11-26 16:40:17,260] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:40:17,278] {logging_mixin.py:109} INFO - [2021-11-26 16:40:17,275] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:40:17,291] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:40:17,293] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.035 seconds
[2021-11-26 16:41:39,401] {processor.py:163} INFO - Started process (PID=17618) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:41:39,401] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:41:39,401] {logging_mixin.py:109} INFO - [2021-11-26 16:41:39,401] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:41:39,416] {logging_mixin.py:109} INFO - [2021-11-26 16:41:39,414] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:41:39,428] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:41:39,431] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 16:43:00,982] {processor.py:163} INFO - Started process (PID=17720) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:43:00,982] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:43:00,982] {logging_mixin.py:109} INFO - [2021-11-26 16:43:00,982] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:43:00,997] {logging_mixin.py:109} INFO - [2021-11-26 16:43:00,995] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:43:01,009] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:43:01,011] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.030 seconds
[2021-11-26 16:44:27,333] {processor.py:163} INFO - Started process (PID=17893) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:44:27,333] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:44:27,333] {logging_mixin.py:109} INFO - [2021-11-26 16:44:27,333] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:44:27,348] {logging_mixin.py:109} INFO - [2021-11-26 16:44:27,346] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:44:27,361] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:44:27,364] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 16:45:49,781] {processor.py:163} INFO - Started process (PID=18003) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:45:49,782] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:45:49,782] {logging_mixin.py:109} INFO - [2021-11-26 16:45:49,782] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:45:49,799] {logging_mixin.py:109} INFO - [2021-11-26 16:45:49,797] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:45:49,811] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:45:49,813] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 16:47:14,010] {processor.py:163} INFO - Started process (PID=18161) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:47:14,010] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:47:14,011] {logging_mixin.py:109} INFO - [2021-11-26 16:47:14,011] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:47:14,026] {logging_mixin.py:109} INFO - [2021-11-26 16:47:14,024] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:47:14,038] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:47:14,040] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 16:48:36,810] {processor.py:163} INFO - Started process (PID=18292) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:48:36,811] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:48:36,811] {logging_mixin.py:109} INFO - [2021-11-26 16:48:36,811] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:48:36,833] {logging_mixin.py:109} INFO - [2021-11-26 16:48:36,831] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:48:36,845] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:48:36,848] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.038 seconds
[2021-11-26 16:50:00,840] {processor.py:163} INFO - Started process (PID=18402) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:50:00,841] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:50:00,841] {logging_mixin.py:109} INFO - [2021-11-26 16:50:00,841] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:50:00,857] {logging_mixin.py:109} INFO - [2021-11-26 16:50:00,855] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:50:00,873] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:50:00,876] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.036 seconds
[2021-11-26 16:51:23,036] {processor.py:163} INFO - Started process (PID=18505) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:51:23,037] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:51:23,037] {logging_mixin.py:109} INFO - [2021-11-26 16:51:23,037] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:51:23,053] {logging_mixin.py:109} INFO - [2021-11-26 16:51:23,051] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:51:23,066] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:51:23,069] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 16:52:44,742] {processor.py:163} INFO - Started process (PID=18608) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:52:44,743] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:52:44,743] {logging_mixin.py:109} INFO - [2021-11-26 16:52:44,743] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:52:44,760] {logging_mixin.py:109} INFO - [2021-11-26 16:52:44,758] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:52:44,772] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:52:44,775] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.032 seconds
[2021-11-26 16:54:07,301] {processor.py:163} INFO - Started process (PID=18716) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:54:07,301] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:54:07,302] {logging_mixin.py:109} INFO - [2021-11-26 16:54:07,302] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:54:07,317] {logging_mixin.py:109} INFO - [2021-11-26 16:54:07,315] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:54:07,329] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:54:07,332] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 16:55:29,084] {processor.py:163} INFO - Started process (PID=18840) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:55:29,084] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:55:29,085] {logging_mixin.py:109} INFO - [2021-11-26 16:55:29,085] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:55:29,099] {logging_mixin.py:109} INFO - [2021-11-26 16:55:29,097] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:55:29,113] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:55:29,115] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
[2021-11-26 16:56:52,510] {processor.py:163} INFO - Started process (PID=18950) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:56:52,511] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:56:52,511] {logging_mixin.py:109} INFO - [2021-11-26 16:56:52,511] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:56:52,527] {logging_mixin.py:109} INFO - [2021-11-26 16:56:52,525] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:56:52,539] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:56:52,543] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.033 seconds
[2021-11-26 16:58:14,773] {processor.py:163} INFO - Started process (PID=19067) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:58:14,773] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:58:14,774] {logging_mixin.py:109} INFO - [2021-11-26 16:58:14,774] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:58:14,792] {logging_mixin.py:109} INFO - [2021-11-26 16:58:14,789] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:58:14,806] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:58:14,809] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.037 seconds
[2021-11-26 16:59:36,864] {processor.py:163} INFO - Started process (PID=19182) to work on /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:59:36,865] {processor.py:625} INFO - Processing file /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py for tasks to queue
[2021-11-26 16:59:36,865] {logging_mixin.py:109} INFO - [2021-11-26 16:59:36,865] {dagbag.py:500} INFO - Filling up the DagBag from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:59:36,879] {logging_mixin.py:109} INFO - [2021-11-26 16:59:36,878] {dagbag.py:334} ERROR - Failed to import: /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
Traceback (most recent call last):
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py", line 84, in <module>
    virtualenv_task = PythonVirtualenvOperator(
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/operators/python.py", line 342, in __init__
    raise AirflowException('PythonVirtualenvOperator requires virtualenv, please install it.')
airflow.exceptions.AirflowException: PythonVirtualenvOperator requires virtualenv, please install it.
[2021-11-26 16:59:36,891] {processor.py:639} WARNING - No viable dags retrieved from /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py
[2021-11-26 16:59:36,894] {processor.py:171} INFO - Processing /Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_python_operator.py took 0.031 seconds
