[2021-11-26 13:20:01,343] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2021-11-26T20:19:40.360596+00:00 [queued]>
[2021-11-26 13:20:01,345] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2021-11-26T20:19:40.360596+00:00 [queued]>
[2021-11-26 13:20:01,345] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-26 13:20:01,345] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-26 13:20:01,345] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-26 13:20:01,350] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-26 20:19:40.360596+00:00
[2021-11-26 13:20:01,353] {standard_task_runner.py:52} INFO - Started process 15601 to run task
[2021-11-26 13:20:01,360] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2021-11-26T20:19:40.360596+00:00', '--job-id', '12', '--raw', '--subdir', '/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T/tmplh0abxwk', '--error-file', '/var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T/tmppphi8b9f']
[2021-11-26 13:20:01,363] {standard_task_runner.py:77} INFO - Job 12: Subtask also_run_this
[2021-11-26 13:20:01,395] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2021-11-26T20:19:40.360596+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-26 13:20:01,413] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T20:19:40.360596+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-26T20:19:40.360596+00:00
[2021-11-26 13:20:01,414] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T
[2021-11-26 13:20:01,415] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2021-11-26T20:19:40.360596+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-26 20:19:40.360596+00:00: manual__2021-11-26T20:19:40.360596+00:00, externally triggered: True>"']
[2021-11-26 13:20:01,427] {subprocess.py:85} INFO - Output:
[2021-11-26 13:20:01,434] {subprocess.py:89} INFO - run_id=manual__2021-11-26T20:19:40.360596+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-26 20:19:40.360596+00:00: manual__2021-11-26T20:19:40.360596+00:00, externally triggered: True>
[2021-11-26 13:20:01,435] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-26 13:20:01,449] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20211126T201940, start_date=20211126T202001, end_date=20211126T202001
[2021-11-26 13:20:01,464] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-26 13:20:01,478] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
