[2021-11-26 13:19:46,834] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2021-11-25T00:00:00+00:00 [queued]>
[2021-11-26 13:19:46,837] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2021-11-25T00:00:00+00:00 [queued]>
[2021-11-26 13:19:46,837] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-26 13:19:46,837] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-26 13:19:46,837] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-26 13:19:46,842] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-25 00:00:00+00:00
[2021-11-26 13:19:46,845] {standard_task_runner.py:52} INFO - Started process 15568 to run task
[2021-11-26 13:19:46,848] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'scheduled__2021-11-25T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', '/Users/danielcollins/opt/anaconda3/lib/python3.8/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T/tmpco5_l5ep', '--error-file', '/var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T/tmp5smrpzoa']
[2021-11-26 13:19:46,850] {standard_task_runner.py:77} INFO - Job 6: Subtask also_run_this
[2021-11-26 13:19:46,879] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this scheduled__2021-11-25T00:00:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-26 13:19:46,902] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-25T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-25T00:00:00+00:00
[2021-11-26 13:19:46,903] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/9_/3lc9lq1570l2_y2nsyxbktvw0000gn/T
[2021-11-26 13:19:46,904] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=scheduled__2021-11-25T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-25 00:00:00+00:00: scheduled__2021-11-25T00:00:00+00:00, externally triggered: False>"']
[2021-11-26 13:19:46,911] {subprocess.py:85} INFO - Output:
[2021-11-26 13:19:46,917] {subprocess.py:89} INFO - run_id=scheduled__2021-11-25T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-25 00:00:00+00:00: scheduled__2021-11-25T00:00:00+00:00, externally triggered: False>
[2021-11-26 13:19:46,918] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-26 13:19:46,931] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20211125T000000, start_date=20211126T201946, end_date=20211126T201946
[2021-11-26 13:19:46,955] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-26 13:19:46,972] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
